# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digger_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Digger(object):
    def setupUi(self, Digger):
        Digger.setObjectName("Digger")
        Digger.resize(1280, 872)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Digger)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Digger)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftLabel = QtWidgets.QLabel(self.groupBox)
        self.leftLabel.setText("")
        self.leftLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.leftLabel.setObjectName("leftLabel")
        self.horizontalLayout.addWidget(self.leftLabel)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.rightLabel = QtWidgets.QLabel(self.groupBox)
        self.rightLabel.setText("")
        self.rightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rightLabel.setObjectName("rightLabel")
        self.horizontalLayout.addWidget(self.rightLabel)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.line_2 = QtWidgets.QFrame(Digger)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_3 = QtWidgets.QGroupBox(Digger)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.calibration_button = QtWidgets.QPushButton(self.groupBox_3)
        self.calibration_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibration_button.sizePolicy().hasHeightForWidth())
        self.calibration_button.setSizePolicy(sizePolicy)
        self.calibration_button.setMinimumSize(QtCore.QSize(92, 0))
        self.calibration_button.setMaximumSize(QtCore.QSize(92, 16777215))
        self.calibration_button.setStyleSheet("font: 14pt \"微软雅黑\";")
        self.calibration_button.setObjectName("calibration_button")
        self.horizontalLayout_2.addWidget(self.calibration_button)
        self.calibration_text = QtWidgets.QLabel(self.groupBox_3)
        self.calibration_text.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.calibration_text.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.calibration_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.calibration_text.setObjectName("calibration_text")
        self.horizontalLayout_2.addWidget(self.calibration_text)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(self.groupBox_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_3.addWidget(self.line_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.laser_h = QtWidgets.QHBoxLayout()
        self.laser_h.setObjectName("laser_h")
        self.deep_warning_2 = QtWidgets.QLabel(self.groupBox_2)
        self.deep_warning_2.setStyleSheet("font: 75 9pt \"微软雅黑\";\n"
"font: 14pt \"微软雅黑\";")
        self.deep_warning_2.setObjectName("deep_warning_2")
        self.laser_h.addWidget(self.deep_warning_2)
        self.laser_led = QtWidgets.QLabel(self.groupBox_2)
        self.laser_led.setStyleSheet("min-width:40px;min-height:40px;max-width:40px;max-height:40px;border-radius:20px;border:1px solid black;background:white")
        self.laser_led.setText("")
        self.laser_led.setObjectName("laser_led")
        self.laser_h.addWidget(self.laser_led)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.laser_h.addItem(spacerItem)
        self.laser_h.setStretch(0, 1)
        self.laser_h.setStretch(1, 4)
        self.laser_h.setStretch(2, 1)
        self.gridLayout.addLayout(self.laser_h, 4, 0, 1, 1)
        self.border_h = QtWidgets.QHBoxLayout()
        self.border_h.setObjectName("border_h")
        self.border_warning = QtWidgets.QLabel(self.groupBox_2)
        self.border_warning.setStyleSheet("font: 75 9pt \"微软雅黑\";\n"
"font: 14pt \"微软雅黑\";")
        self.border_warning.setObjectName("border_warning")
        self.border_h.addWidget(self.border_warning)
        self.edge_led = QtWidgets.QLabel(self.groupBox_2)
        self.edge_led.setMinimumSize(QtCore.QSize(42, 42))
        self.edge_led.setStyleSheet("min-width:40px;min-height:40px;max-width:40px;max-height:40px;border-radius:20px;border:1px solid black;background:white")
        self.edge_led.setText("")
        self.edge_led.setObjectName("edge_led")
        self.border_h.addWidget(self.edge_led)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.border_h.addItem(spacerItem1)
        self.border_h.setStretch(0, 1)
        self.border_h.setStretch(1, 4)
        self.border_h.setStretch(2, 1)
        self.gridLayout.addLayout(self.border_h, 0, 0, 1, 1)
        self.gps_h = QtWidgets.QHBoxLayout()
        self.gps_h.setObjectName("gps_h")
        self.gps_warning_3 = QtWidgets.QLabel(self.groupBox_2)
        self.gps_warning_3.setStyleSheet("font: 75 9pt \"微软雅黑\";\n"
"font: 14pt \"微软雅黑\";")
        self.gps_warning_3.setObjectName("gps_warning_3")
        self.gps_h.addWidget(self.gps_warning_3)
        self.gps_led = QtWidgets.QLabel(self.groupBox_2)
        self.gps_led.setStyleSheet("min-width:40px;min-height:40px;max-width:40px;max-height:40px;border-radius:20px;border:1px solid black;background:white")
        self.gps_led.setText("")
        self.gps_led.setObjectName("gps_led")
        self.gps_h.addWidget(self.gps_led)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gps_h.addItem(spacerItem2)
        self.gps_h.setStretch(0, 1)
        self.gps_h.setStretch(1, 4)
        self.gps_h.setStretch(2, 1)
        self.gridLayout.addLayout(self.gps_h, 2, 0, 1, 1)
        self.deep_h = QtWidgets.QHBoxLayout()
        self.deep_h.setObjectName("deep_h")
        self.deep_warning = QtWidgets.QLabel(self.groupBox_2)
        self.deep_warning.setStyleSheet("font: 75 9pt \"微软雅黑\";\n"
"font: 14pt \"微软雅黑\";")
        self.deep_warning.setObjectName("deep_warning")
        self.deep_h.addWidget(self.deep_warning)
        self.deep_led = QtWidgets.QLabel(self.groupBox_2)
        self.deep_led.setStyleSheet("min-width:40px;min-height:40px;max-width:40px;max-height:40px;border-radius:20px;border:1px solid black;background:white")
        self.deep_led.setText("")
        self.deep_led.setObjectName("deep_led")
        self.deep_h.addWidget(self.deep_led)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.deep_h.addItem(spacerItem3)
        self.deep_h.setStretch(0, 1)
        self.deep_h.setStretch(1, 4)
        self.deep_h.setStretch(2, 1)
        self.gridLayout.addLayout(self.deep_h, 0, 1, 1, 1)
        self.gyro_h = QtWidgets.QHBoxLayout()
        self.gyro_h.setObjectName("gyro_h")
        self.gyro_warning = QtWidgets.QLabel(self.groupBox_2)
        self.gyro_warning.setStyleSheet("font: 75 9pt \"微软雅黑\";\n"
"font: 14pt \"微软雅黑\";")
        self.gyro_warning.setObjectName("gyro_warning")
        self.gyro_h.addWidget(self.gyro_warning)
        self.gyro_led = QtWidgets.QLabel(self.groupBox_2)
        self.gyro_led.setStyleSheet("min-width:40px;min-height:40px;max-width:40px;max-height:40px;border-radius:20px;border:1px solid black;background:white")
        self.gyro_led.setText("")
        self.gyro_led.setObjectName("gyro_led")
        self.gyro_h.addWidget(self.gyro_led)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gyro_h.addItem(spacerItem4)
        self.gyro_h.setStretch(0, 1)
        self.gyro_h.setStretch(1, 4)
        self.gyro_h.setStretch(2, 1)
        self.gridLayout.addLayout(self.gyro_h, 2, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.groupBox_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.line_5 = QtWidgets.QFrame(self.groupBox_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setStyleSheet("font: 75 12pt \"微软雅黑\";")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.time = QtWidgets.QLabel(self.groupBox_3)
        self.time.setStyleSheet("font: 75 9pt \"微软雅黑\";\n"
"font: 14pt \"微软雅黑\";")
        self.time.setObjectName("time")
        self.verticalLayout_3.addWidget(self.time)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 5)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 2)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 1)

        self.retranslateUi(Digger)
        self.calibration_button.clicked.connect(self.calibration_text.show)
        QtCore.QMetaObject.connectSlotsByName(Digger)

    def retranslateUi(self, Digger):
        _translate = QtCore.QCoreApplication.translate
        Digger.setWindowTitle(_translate("Digger", "挖掘机·"))
        self.calibration_button.setText(_translate("Digger", "校准"))
        self.calibration_text.setText(_translate("Digger", "校准按钮使用说明："))
        self.deep_warning_2.setText(_translate("Digger", "激光信号"))
        self.border_warning.setText(_translate("Digger", "边界提示"))
        self.gps_warning_3.setText(_translate("Digger", "定位信号"))
        self.deep_warning.setText(_translate("Digger", "深度提示"))
        self.gyro_warning.setText(_translate("Digger", "陀螺仪信号"))
        self.label.setText(_translate("Digger", "说明：红灯表示超出。。。。。"))
        self.time.setText(_translate("Digger", "time"))

